### ISSUE TITLE
encrypt files

### ISSUE THREAD

**Issue by Krysztophe** [orgrim/pg_back#57]
Encrypting a single file is complicated, but it would be nice if pg_back could encrypt the dumps itself (GPG ?)

In an ideal case, the dump would not touch the disk un-encrypted (I have no idea how to deal with the directory format in this case).

**Comment by orgrim** [comment]
Hello,

How will the files be decrypted?

**Comment by Krysztophe** [comment]
Obviously, the decrypting key must be provided one way or the other. How did you do with pitrery? (I haven't looked)

**Comment by orgrim** [comment]
pitrery uses gpg, so the private key must in the keyring of the user who does the restore and runs the postmaster. I find it quite hard to setup. Other tools like pgbackrest use AES with a passphrase.

**Comment by orgrim** [comment]
@Krysztophe could you please have a look at PR #62 that add encryption?

Unencrypted files are stored on disk while pg_back is running, I don't think it is an issue because pg_back is best run on the same machine as PostgreSQL, which should be secure, the user just have to ensure the backup directory has mode 700. Just encrypting produced files is easier to implement, it is done asynchronously.

Regards

**Comment by Krysztophe** [comment]
Thanks! I'll try to test before the end of the month.

**Comment by orgrim** [comment]
@Krysztophe any news? Thanks.

**Comment by orgrim** [comment]
I have other changes to push so I'm merging this. You can still review it when you find the time.

Thanks

**Comment by Krysztophe** [comment]
Some tests in #64
